### ISSUE TITLE
I have tried in my local but still confused. Chat icon of the app not visible on my site. How to use it?

### ISSUE THREAD

**Issue by pantcr7** [clefincode/clefincode_chat#1]

**Comment by clefincode** [comment]
Thank you for your feedback, Can you give me more details about the frappe version and the Ubuntu version?
And if you like, I can support you online by remotely Connect to your device
You can reach me at:
t: +971585997930
e: ahmad@clefincode.com

**Comment by pantcr7** [comment]
Frappe Version 15
Ubuntu Version  22.04.4 LTS

**Comment by clefincode** [comment]
Hi, still need help? you can reach me to support you with your installation
Regards,

**Comment by hamzahabeeb** [comment]
i am facing the same issue, i dont see the chat icon

**Comment by clefincode** [comment]
@hamzahabeeb Hi, please make sure to run 
bench migrate
bench build
bench restart
after installation
and one thing to note administrator user cannot the chat so you wont see the icon
let me know if you need further help

**Comment by hamzahabeeb** [comment]
Thanks its working now,

was trying to access it through admin login.

**Comment by clefincode** [comment]
you can use mobile app with your server:
Android:
https://play.google.com/store/apps/details?id=com.clefincode.chat&hl=en&gl=US
IOS:
https://apps.apple.com/ae/app/clefincode-chat/id6478499855

**Comment by hamzahabeeb** [comment]
sure thanks, but i have one more doubt.

Is there a way i can restrict the number of contacts a user can send messages to?

**Comment by clefincode** [comment]
We have implemented a restriction for customers and suppliers on our platform. When they attempt to communicate through the website, any portal, or even if they are granted access to your disk, they will only be able to communicate with contacts who are registered users of the system. They will not be able to interact with other customers or suppliers outside of this network.

If you require further restrictions, such as limiting users to communicate only within specific groups, this functionality is not currently available. However, it's a valuable suggestion, and we may consider implementing it in the future. For now, our platform is open source, and you are welcome to customize it to meet your needs. Please continue to sync with our repository for future updates and new features.

**Comment by hamzahabeeb** [comment]
please do look into it as it is a very basic function, we cant allow every contact to communicate with each other

**Comment by prabanjan** [comment]
I am also facing same issue, I have Installed Frappe ERPnext 15 version in Oracle VirtualBox and I have installed clefincode chat as well but not working for me. 

<img width="499" height="449" alt="Image" src="https://github.com/user-attachments/assets/bd2f08e5-f8bd-488a-8710-e5a85f140f94" />
