### ISSUE TITLE
get_view_logs() requires 1 argument, but 2 were given

### ISSUE THREAD

**Issue by MA-INDUSTRIE** [clefincode/clefincode_chat#3]
Dear Sir's,

thank you for creating this great app. I installed the following versions:

ClefinCode Chat: v0.0.2 (HEAD)
ERPNext: v15.26.1 (HEAD)
ERPNext Germany: v15.3.1 (HEAD)
Frappe Framework: v15.29.0 (HEAD)
Frappe HR: v15.22.0 (HEAD)

TypeError: get_view_logs() takes 1 positional argument but 2 were given
Possible source of error: clefincode_chat (app)

The error message appears at several actions, for example after user, login or when I try to open a doctype.

Best regards,

Michael

**Comment by clefincode** [comment]
Hi, Thanks for your feedback. We will check and update you soon.
Best Regards,
Ahmad

**Comment by clefincode** [comment]
Hi, We have made the update
You can check your frappe cloud  and update the app
Regards,

**Comment by MA-INDUSTRIE** [comment]
Thank you guy's! Not only for the awesome plugin, but also for your quick reaction!

**Comment by clefincode** [comment]
You are so welcome
A nice comment and review from you on Frappe Cloud marketplace would be great

**Comment by MA-INDUSTRIE** [comment]
I would love to, but there appears a 404 Error.

**Comment by clefincode** [comment]
Frappe is doing some updates on the marketplace, maybe later
Meanwhile, you are welcome to use the new chat APP on mobile 
Android:
https://play.google.com/store/apps/details?id=com.clefincode.chat&hl=en&gl=US
IOS:
https://apps.apple.com/ae/app/clefincode-chat/id6478499855

For more information about features that you can use, please check:
https://clefincode.com/pages/clefincode_chat_docs
